### ISSUE TITLE
Bug: Attack Rolls

### ISSUE THREAD

**Issue by roguedevjake** [reonZ/pf2e-perception#19]
Foundry: 11.308
PF2e: 5.4.4
Modules: PF2e Perception (0.6.1)

Issue:
Strikes and Spell attacks against a targeted enemy aren't sent to chat unless the target is in bright (not dim) light. Darkvision and other sight types do not impact this either. 

```
Uncaught (in promise) TypeError: undefined. game.pf2e.Check.createResultFlavor is not a function
[Detected 2 packages: pf2e-perception, system:pf2e]
    at CheckPF2e.checkRoll (check.js:42:35)
    at async Object.roll (pf2e.mjs:54:251484)
    at async HTMLButtonElement.<anonymous> (pf2e.mjs:1:348341)
checkRoll @ check.js:42
```

**Comment by reonZ** [comment]
well considering we are at version `0.24.0`, that doesn't surprise me much that you encounter some bugs...
