### ISSUE TITLE
[Bug] Comaptaibility with PF2e Ranged Combat

### ISSUE THREAD

**Issue by cadowtin** [reonZ/pf2e-perception#2]
![image](https://github.com/reonZ/pf2e-perception/assets/79132112/9cd513c4-e1cf-4ab7-a89c-83a6fda43821)

**Comment by cadowtin** [comment]
occurs when NPC strikes PC

**Comment by reonZ** [comment]
this issue is unrelated to the `PF2e Ranged Combat` module and was fixed in the `0.6.1` update
