### ISSUE TITLE
Feature Request: Aim-Aiding Rune

### ISSUE THREAD

**Issue by uLotUu** [reonZ/pf2e-perception#22]
"Armor etched with this rune aids in routing ranged attacks aimed at an enemy around you. You don't provide enemies cover against your allies' ranged attacks."

Don't know if its possible to exclude 1 party member from giving covers to enemies.

**Comment by reonZ** [comment]
i have added a new RE for this in version `0.25.0` called `ignored`, you can find the RE for `Aim-Aiding Rune` [here](https://github.com/reonZ/pf2e-perception/wiki#aim-aiding-rune)
