### ISSUE TITLE
[Bug] Can't roll from character sheet when the canvas is disabled

### ISSUE THREAD

**Issue by Rowiz49** [reonZ/pf2e-perception#26]
When this module is active players with the canvas disabled can't roll from their sheets.

**Comment by reonZ** [comment]
correct me if i am wrong, but this module has no practical use without canvas, everything is token based.

**Comment by Rowiz49** [comment]
That's true, but for in person play where the players have only their character sheets and Foundry is only displayed with canvas enabled on a TV and the GM's computer it's really convenient to have the players roll their skills or iniative on their own. I do admit it is an edge case and understand if it's not planned.

**Comment by reonZ** [comment]
I can probably find a fix for it.

My point was more about the fact that if players don't have canvas and therefore no tokens, they will never take make use of any of the module's features, so what is the point of using the module to begin with ?

**Comment by Rowiz49** [comment]
The GM has to do the attack and token related rolls of the players for them from their computer, but it's nice if the players can fill in their own initiative and non-token related rolls from their own device.

**Comment by reonZ** [comment]
i see, i will try to find a way, i dunno how doable this is though

**Comment by Rowiz49** [comment]
Thank you! This is the error I get when i try to roll:
![image](https://github.com/reonZ/pf2e-perception/assets/93596067/096ed942-5535-44d1-99b3-bfdaaa24a073)

**Comment by reonZ** [comment]
Completely forgot about this, sorry for the wait :/

**Comment by Rowiz49** [comment]
Thank you so much for the fix!!
