### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Monachus** [reonZ/pf2e-perception#31]
Hi Idle, Love the module!

Would appreciate if the option to make the token look in a similar way to how Tremorsense core detectionMode works when the token is hidden. I would be more than happy to fork it and do the push request but I still have not reversed engineered the tremorsense DetectionMode.

**Comment by reonZ** [comment]
Not sure i understand the request, do you just want to change the color of hidden tokens ? because that wouldn't be related to this module if so.
