### ISSUE TITLE
Per Player Cover is being done differently than in the system - found by testing with phase bolt and rule elements

### ISSUE THREAD

**Issue by Peach774** [reonZ/pf2e-perception#32]
Phase Bolt goes through 2 AC of circumstance bonuses (such as that from standard or lesser cover). 

In order to implement this in game, I have created an effect that looks like this:
`{"key":"AdjustModifier","selector":"ac","mode":"subtract","value":2,"predicate":["bonus:type:circumstance"]}`
and then created an ephemeral effect that references the effect above:
`{"key":"EphemeralEffect","uuid":"UUID-GOESHERE","selectors":["spell-attack-roll"],"predicate":["item:slug:phase-bolt"]}` which I have placed on a feat on the character casting phase bolt.

When giving an enemy the standard or lesser cover effect using the system buff, this functions correctly and removes the circumstance bonus added by said cover:
![image](https://github.com/reonZ/pf2e-perception/assets/5171184/c60f8e30-52ed-4d15-b809-3db743f3922a)

When doing this with the perception menu and setting the enemy to have standard cover versus the player with the ephemeral effect, this does not work:
![image](https://github.com/reonZ/pf2e-perception/assets/5171184/0e98897c-09b7-42a2-a584-19d074250cf5)

I believe this is either caused by perception adding cover to the enemy's AC after the stage where it would be reduced by rule elements or because perception is not correctly setting cover as a circumstance bonus.

I hope I did enough explaining to make this clear and hopefully easy to fix. Thank you <3

**Comment by reonZ** [comment]
Nothing i can do about it really

**Comment by K9GM3** [comment]
@Peach774 You can make a work-around to this issue by putting rules elements in Phase Bolt. They'll cancel any automated or conditional lesser/standard cover, and if you've given the creature conditional greater cover, that'll get downgraded to standard cover.

`{"key":"PF2ePerception","type":"cover","selector":"cancel","targets":["lesser","standard"],"affects":"other","predicate":["item:slug:phase-bolt"]}`

`{"key":"PF2ePerception","type":"cover","selector":"reduce","targets":"greater","affects":"other","predicate":["item:slug:phase-bolt"]}`
