### ISSUE TITLE
Hiding from Allies

### ISSUE THREAD

**Issue by K9GM3** [reonZ/pf2e-perception#34]
Currently, the Hide action only targets enemies by default. Unless allies are specifically selected as targets, they won't be considered for vision changes. I believe this may be a bug, since Hiding typically has you roll against all creatures regardless of allegiance.

![afbeelding](https://github.com/reonZ/pf2e-perception/assets/110890313/003eaaf6-0c25-4978-9b5e-e208fbb5c732)
![afbeelding](https://github.com/reonZ/pf2e-perception/assets/110890313/2ed8dd33-a9f0-41ae-8c9d-fcccecd41825)

It's not a huge problem since targeting can help get around it, but would it be possible to have Hide target all creatures by default?

**Comment by reonZ** [comment]
Closing this, this module isn't getting any more work beside the eventual fix to keep it afloat.
