### ISSUE TITLE
[Feature Request] Standing Characters provide Cover to Prone Characters

### ISSUE THREAD

**Issue by apoapostolov** [reonZ/pf2e-perception#36]
Option that is frequently used to protect fallen allys is to stand in the same square and take attacks from enemies, or at least provide cover if someone is trying to finish off the fallen allies. 

This would check if the square of a Prone character is shared with a Standing Character that is an ally, and provide Standard Cover.

**Comment by reonZ** [comment]
Never seen such rule.
