### ISSUE TITLE
Change multiple at once or Reset All

### ISSUE THREAD

**Issue by HavocsCall** [reonZ/pf2e-perception#41]
Is there a way to change multiple or just "Reset ALL" button? There have been cases where a player hides, but it defaults to all tokens on the scene. I'd like to be able to change all at once or just reset all without having to click each one.

**Comment by reonZ** [comment]
Yes, just look a bit better, the menu has a few selection options and tricks.

**Comment by HavocsCall** [comment]
I found it by luck. Either my vision or my monitor is messed up, but I really can't see it even knowing where it is. Would it be a big ask to give it an outline or a little bit more contrast?

**Comment by reonZ** [comment]
I don't work on this module anymore, haven't for a very long time now.

I only fix the occasional bugs or breaking changes due to system updates.
