### ISSUE TITLE
[Feature] Support for automated Hide/Sneak and Search

### ISSUE THREAD

**Issue by apoapostolov** [reonZ/pf2e-perception#5]
- Macro to Hide/Sneak and Search, with the last rolled value recorded at the token level and compared to visible tokens and selected tokens
- Macro to Search, comparing result value to all Hide/Search values of visible tokens and selected tokens
- Comparison used to assign personalized hidden conditions (perhaps with some filtering to avoid applying to the whole scene - such as using current combat encounter or sight calculation).

**Comment by reonZ** [comment]
all of that is already in the module...
