### ISSUE TITLE
Feature request : Invisibility/See invisibility integration

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-perception#6]
Hi, would that be possible to add support for the invisible condition and see invisibility spell effect ?

Now when invisible and a token with see invisibility attacks it does a flat-check vs hidden, but it should be cancealed :
![image](https://github.com/reonZ/pf2e-perception/assets/65986545/ed6d355d-6ab6-435c-ba35-8d5abdd729df)

There is also this rule about invisibility : "A creature with the invisible condition (by way of an [invisibility](https://2e.aonprd.com/Spells.aspx?ID=164) spell or [invisibility potion](https://2e.aonprd.com/Equipment.aspx?ID=187), for example) >is automatically undetected< to any creatures relying on sight as their only precise sense. Precise senses other than sight ignore the invisible condition.

You can use the Seek basic action to attempt to figure out an invisible creature’s location, making it instead only hidden from you. This lasts until the invisible creature successfully uses Sneak to become undetected again. >If you’re already observing a creature when it becomes invisible, it starts out hidden<, since you know where it was when it became invisible, though it can then Sneak to become undetected."

**Comment by reonZ** [comment]
The thing is, when you put the `invisible` condition in the system, creatures are `hidden` and not `undetected`.

I will have to look about it more, not sure how to handle that.

**Comment by reonZ** [comment]
I don't override cover effect, you can still use the regular system cover, which you can do also with invisible, just don't use the invisible condition and instead set the conditional visibility manually

Now the issue lays in the fact that without the invisibility condition on the token, there is no way to implement the exceptions that comes with it.

**Comment by apoapostolov** [comment]
Maybe option to make any token that is Hidden and moves become immediately Undetected?
