### ISSUE TITLE
Feature request : Sneak

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-perception#7]
Hi, would that be possible to add support for the "Sneak" action ?

https://2e.aonprd.com/Actions.aspx?ID=63

Here are some feats that impact the sneak action : 

https://2e.aonprd.com/Feats.aspx?ID=785
https://2e.aonprd.com/Feats.aspx?ID=807
https://2e.aonprd.com/Activities.aspx?ID=1
https://2e.aonprd.com/Feats.aspx?ID=579

Edit : https://2e.aonprd.com/Actions.aspx?ID=45

Sneak also interacts with invisible condition since an invisible creature who do anything but sneak or nothing becomes hidden instead of undetected.

**Comment by apoapostolov** [comment]
Sneak contains in itself a Stealth check to Hide, so yes it must be treated the same way as Hide
